#!/usr/bin/perl

### BEGIN INIT INFO
# Provides:          fivem
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: FiveM service 1.0
# Description:       FiveM service 1.0
# Documentation:     https://gameplayer.club
# Type:              forking
# X-Interactive:     false
### END INIT INFO

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 1, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

my $FIVEMDIR = "/home/fivemowner/fivem_resources";
my $KILL_COMMAND = "killall server.cfg";

my $Command = $ARGV[0];
if ($Command eq "")
{
	$Command = "NONE";
}

my $running=`ps ax|grep server.cfg|grep -v grep`;

chdir ("$FIVEMDIR");

if ($Command eq "start")
{
	if ($running eq "")
	{
		print "Starting FiveM...\n";
		if (-f "$FIVEMDIR/nostart")
		{
			print "Removing $FIVEMDIR/nostart\n";
			# Remove the lock file if it exists
			unlink("$FIVEMDIR/nostart");
		}
		# Start the screen process
		system("nohup $FIVEMDIR/startfivem > /tmp/FiveMStartup.log\&");
	}
}
elsif ($Command eq "stop")
{
	print "Stopping FiveM process...\n";
	system("touch '$FIVEMDIR/nostart'");
	if ($running ne "")
	{
		# Process is running, kill it
		system($KILL_COMMAND);
		sleep(10);
	}
}
elsif ($Command eq "restart")
{
	if (-f "$FIVEMDIR/nostart")
	{
		print("Removing $FIVEMDIR/nostart\n");
		unlink("$FIVEMDIR/nostart");
	}
	if ($running ne "")
	{
		system($KILL_COMMAND);
		sleep(10);
	}
}
elsif ($Command eq "status")
{
	if ($running ne "")
	{
		print("FiveM Server Running\n");
	}
	else
	{
		print("FiveM Server Not Running\n");
	}
}
else
{
	print ("Uknown command '$Command'\n");
	print ("Usage: $0 {start|status|stop|restart}\n");
	exit(1);
}

exit(0);
