#!/usr/bin/perl

### BEGIN INIT INFO
# Provides:          lugdunon
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Lugdunon service 1.0
# Description:       Lugdunon service 1.0
# Documentation:     https://synchronetbbs.org/index.php/forum/alternate-startup-scripts
# Type:              forking
# X-Interactive:     false
### END INIT INFO

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 1, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

my $LUGDUNONDIR = "/root/lugdunon";
# Read in host name
my $HOSTFILE = "/etc/hostname";
open FILE, $HOSTFILE or die "Couldn't open file: $HOSTFILE";
my $HOST = <FILE>;
close FILE;
chop($HOST);

my $KILL_COMMAND = "/usr/bin/wget -O /dev/null http://$HOST:41976/management/CORE.COMMAND.SHUTDOWN?mode=now";

my $Command = $ARGV[0];
if ($Command eq "")
{
	$Command = "NONE";
}

my $running=`ps ax|grep net.lugdunon.Server|grep -v grep`;

if ($Command eq "start")
{
	if ($running eq "")
	{
		print "Starting Lugdunon...\n";
		if (-f "$LUGDUNONDIR/nostart")
		{
			print "Removing $LUGDUNONDIR/nostart\n";
			# Remove the lock file if it exists
			unlink("$LUGDUNONDIR/nostart");
		}
		# Start the screen process
		system("nohup $LUGDUNONDIR/startlugdunon > /tmp/LugdunonStartup.log\&");
	}
}
elsif ($Command eq "stop")
{
	print "Stopping Lugdunon process...\n";
	system("touch '$LUGDUNONDIR/nostart'");
	if ($running ne "")
	{
		# Process is running, kill it
		system($KILL_COMMAND);
		sleep(10);
	}
}
elsif ($Command eq "restart")
{
	if (-f "$LUGDUNONDIR/nostart")
	{
		print("Removing $LUGDUNONDIR/nostart\n");
		unlink("$LUGDUNONDIR/nostart");
	}
	if ($running ne "")
	{
		system($KILL_COMMAND);
		sleep(10);
	}
}
elsif ($Command eq "status")
{
	if ($running ne "")
	{
		print("Lugdunon Server Running\n");
	}
	else
	{
		print("Lugdunon Server Not Running\n");
	}
}
else
{
	print ("Uknown command '$Command'\n");
	print ("Usage: $0 {start|status|stop|restart}\n");
	exit(1);
}

exit(0);
