#!/usr/bin/perl

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 1, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

my $FIVEMDIR = "/root/server-data";
my $SCREENCMD = "/usr/bin/screen";

# No changes below here...

my $startpath = $ENV{'PATH'};
my $newpath = "$FIVEMDIR/exec:$startpath";
my $exists = "";

# Set ENV vars
$ENV{'PATH'} = $newpath;
$ENV{'TERM'} = "xterm-256color";

my $running=`ps ax|grep server.cfg|grep -v grep`;

# check if FiveM process is running
if ($running ne "")
{
	print ("Startupscript already running...\n");
	exit (0);
}

while (-1)
{
	chdir $FIVEMDIR;
	# check if FiveM process is running
	$running=`ps ax|grep server.cfg|grep -v grep`;
	if ($running eq "")
	{
		print "FiveM not running\n";
		# See if they want the server started
		if (! -f "$FIVEMDIR/nostart")
		{
			# The Log Entry
			my $datestring = localtime();
			my $TIME="FiveM Down, Restarting: $datestring";
			open(OUTF, ">>$FIVEMDIR/FiveMScreen.log") || die "Unable to open $FIVEMDIR/FiveMScreen.log for appending";
			print (OUTF "$TIME\n");
			close($OUTF);
			chdir $FIVEMDIR;
			print "Starting screen process\n";
			system("$SCREENCMD -fa -S FiveM -d -U -m /root/fivem/run.sh +exec server.cfg");
		}
	}
	# Sleep for 1 minute before checking again
	sleep(60);
}
exit(0);
